Curtis-Thomas/free-api-list-with-react

src/core/footer/Footer.js

Added Footer file
https://github.com/Curtis-Thomas/free-api-list-with-react/issues/3

Update Footer Styling #3

---

src/core/main/navigation/Link.js
src/core/main/navigation/NavBar.js

- move link handler and use MUI's Link component
- add labels to routes in navbar for clarity
#9 
- [ x ] I have tested my changes locally.
- [ x ] My code follows the project's coding conventions and style guidelines.
- more of a development enhancement than visual, please advise what styling edits you would like

move link handler and use MUI's Link component. add labels for clarity

---

src/documentation/ContributorsContent.js

Adding myself to the list of contributors.
None.
None.

Add contributor

---

src/tools/AdvancedBoxTestCrud.js
src/tools/BoxTestImg.js

This pull request will resolve the issue #42 and #41
List any related issues or pull requests that are being addressed.
I hope the code works fine.

removed hover effect

---

src/documentation/ContributorsContent.js

Thank you so much for the clear instructions.  
added myself as a contributor
List any related issues or pull requests that are being addressed.

Added myself as contributer - sneha chitre

---

src/documentation/ContributorsContent.js

Added myself as contributor to the project.
https://github.com/Curtis-Thomas/free-api-list-with-react/issues/3

AddContributor

---

src/api/cryptocurrency/1Cryptocurrency.txt

Removed list of API's that weren't free, required an API key or signup.
#23
- Some API's (namely CoinDCX, CoinGecko, Coinpaprika, Messari, NocaDax and VALR) can be used with or without an API key so I decided to included them in the list.
- The MercadoBitcoin API (https://www.mercadobitcoin.com.br/api-doc/) website is in Portugese.

Sanitize CryptoCurrency API's

---

src/api/calendar/1Calendar.txt

Removed list of API's that weren't free, required an API key or signup.
#22
- The Czech Nameday Calendar website (https://svatky.adresa.info/) is in Czech.
- I changed the UK Bank Holidays website from (https://github.com/egno/work-calendar) to (https://www.gov.uk/help/reuse-govuk-content).

Sanitize Calendar API's

---

src/api/gamesComics/1GamesComics.txt

The Cross Universe API in 1GamesComics.txt has since moved to a different URL.
This PR updates it to point to that new one.
none

CrossUniverse API moved

---

src/core/header/Header.js

Describe the purpose and scope of your pull request.
List any related issues or pull requests that are being addressed.
- [ ✓] I have tested my changes locally.
- [ ✓] I have added necessary documentation or updated existing documentation.
- [ ✓] My code follows the project's coding conventions and style guidelines.
- [ ✓] All tests pass successfully.
- [ ✓] I have added/updated relevant unit tests.

changed FAR to Free API List

---

src/core/footer/Footer.js

Add dynamic year update functionality to the footer component, so that the copyright year doesn't need to be updated manually.
#77
This was my first OSS contribution ever, I hope everything is in order.

feat: add dynamic year functionality to the footer component

---

src/core/header/Header.js

Modified the header file based on the requests of the issue #69
Created a menu for the tools. docs, night mode switch. Made the switch stay toggled when you close the menu, depending on the current theme. Added descriptions next to the icons and margins.
Issue #69 "Enhance Styling of Header Component"
- [True] I have tested my changes locally.
- [True] I have added necessary documentation or updated existing documentation.
- [True] My code follows the project's coding conventions and style guidelines.
Seeking constructive feedback on my pull request—appreciate any insightful criticism to improve the header and the over all code. Thank you!

Header modifications, Issue #69 "Enhance Styling of Header Component"

---

src/components/BtnRouting.js

Enhance the styling of the BtnRouting component. If you find it unsatisfactory, gimme me some suggestions :)

Enhance styling of BtnRouting button   #58

---

src/core/header/Header.js

- cleaned out the code structure
- added the documentation for the Header component
- added relevant comments  where necessary
Header component's usage is well-documented, and comments have been to improve code readability.
Update Documentation in Header Component #71 code path => src/core/Header.js
- [✔] I have tested my changes locally.
- [✔] I have added necessary documentation or updated existing documentation.
- [✔] My code follows the project's coding conventions and style guidelines.
- [✔] All tests pass successfully.
- [✔] I have added/updated relevant unit tests.
lemme know if you need additional changes

Updated Header.js

---

src/core/main/BoxApiInfo.js

Reviewed the component's documentation and comments.
Updated and improve documentation where necessary.
Added comments to clarify the purpose of different parts of the code.
Issue Description:
Ensure that the BoxApiInfo component's usage is well-documented, and add comments to improve code readability.

#67 Updated Documentation in BoxApiInfo Component to make it more readable

---

src/App.js
src/api/dictionary/Dictionary1Dash.js
src/api/dictionary/DictionaryFreeDictionary.js
src/core/main/Main.js

Added Free Dictionary API from the dictionaries array in the dictionary folder while also utilizing a consistent layout to enhance user experience and ease of navigation. Will also be adding the rest of the dictionary API's in this week
Standardize Layout and Populate Content for Dictionary API Pages #80
Below are the screenshots for the local working application with dictionary api page

Added Free Dictionary API page in the dictionary folder #80

---

src/core/main/BoxApiInfo.js

Issue #65: Enhanced Styling of BoxApiInfo Component
The styling of the BoxApiInfo component are improved to enhance its visual appeal and user experience.
Reviewed and updated the Material-UI styles applied to the component.
Adjusted margins, and padding, or added styling enhancement.
List any related issues or pull requests that are being addressed.

Enhanced Styling of BoxApiInfo Components,  fixes #65

---

public/index.html

#81 
@Curtis-Thomas 
@aditya-armal
I have reviewed the meta description and enhanced the way it is framed.

Updated meta description in public/index.html

---

src/api/finance/Finance1Dash.js

added theme color to Finance dash component
add theme coloring to Finance dash #127

style: theme coloring added to Finance1Dash

---

src/api/jobs/Jobs1Dash.js
src/api/machineLearning/MachineLearning1Dash.js
src/api/music/Music1Dash.js

Fix issue 136

---

src/api/music/Music1Dash.js

theme coloring added to Music1Dash.

style: theme coloring added to Music1Dash

---

src/api/machineLearning/MachineLearning1Dash.js
src/api/music/Music1Dash.js

Describe the purpose and scope of your pull request.
Add theme to MachineLearning1Dash.

Fix issue 137

---

src/api/foodDrink/FoodDrink1Dash.js
src/api/government/Government1Dash.js
src/api/jobs/Jobs1Dash.js
src/api/machineLearning/MachineLearning1Dash.js
src/api/music/Music1Dash.js

Fix issue 128

---

src/api/government/Government1Dash.js
src/api/jobs/Jobs1Dash.js
src/api/machineLearning/MachineLearning1Dash.js
src/api/music/Music1Dash.js

Add theme to Government1Dash.js .

Fix issue 135
